sonar.organization=camilobr89
sonar.projectKey=camilobr89_code-insight-ai-web
sonar.projectName=code-insight-ai-web
sonar.host.url=https://sonarcloud.io

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.spec.ts,src/environments/**

sonar.javascript.lcov.reportPaths=coverage/code-insight-ai-web/lcov.info
sonar.sourceEncoding=UTF-8
